Sprint IC integration
hmcts/et-ccd-definitions-scotland pull request #119
Opened 2022-07-05 16:09 UTC by pmumbere

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-2025
https://tools.hmcts.net/jira/browse/RET-2027
https://tools.hmcts.net/jira/browse/RET-2028
https://tools.hmcts.net/jira/browse/RET-2029
https://tools.hmcts.net/jira/browse/RET-2037
https://tools.hmcts.net/jira/browse/RET-2045
https://tools.hmcts.net/jira/browse/RET-2047

### Change description ###
Initial consideration Rule 26 pages

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-07-05 17:39 UTC, Itay-Kirsh requested changes

2022-07-05 17:39 UTC, Itay-Kirsh commented on definitions/json/CaseEventToFields.json
> +
What are these line breaks for?

2022-07-05 17:39 UTC, Itay-Kirsh commented on definitions/json/CaseEventToFields.json
> +    "CaseFieldID": "etInitialConsiderationRespondent",
Change etInitialConsideration to etIC for the first few fields as this is the convention in the rest of the commit. With Ctrl+F found 61 cases of etInitialConsideration and 310 of etIC.

2022-07-06 06:40 UTC, pmumbere commented on definitions/json/CaseEventToFields.json
> +
I think happened post merge. Now resolved

2022-07-06 06:42 UTC, pmumbere commented on definitions/json/CaseEventToFields.json
> +    "CaseFieldID": "etInitialConsiderationRespondent",
We are aware. However, we have already made changes to data model and callbacks etc. We will carry out a refactoring exercise later on

2022-07-06 08:22 UTC, Itay-Kirsh approved these changes

2022-07-06 08:36 UTC, hsjhita approved these changes

2022-07-06 09:03 UTC, hsjhita commented on definitions/json/ComplexTypes.json
> +    "FieldType": "MultiSelectList",
FixedRadioList according to Sigma

2022-07-06 09:04 UTC, hsjhita commented on definitions/json/ComplexTypes.json
> +    "FieldType": "MultiSelectList",
FixedRadioList according to Figma

2022-07-06 12:47 UTC, pmumbere commented on definitions/json/ComplexTypes.json
> +    "FieldType": "MultiSelectList",
Fixed

2022-07-06 12:47 UTC, pmumbere commented on definitions/json/ComplexTypes.json
> +    "FieldType": "MultiSelectList",
Fixed

2022-07-06 12:50 UTC, Itay-Kirsh approved these changes

2022-07-06 12:50 UTC, hsjhita commented on definitions/json/AuthorisationCaseField.json
> +    "CRUD": "R"
missing auth for caseworker-employment-api

2022-07-06 12:56 UTC, pmumbere commented on definitions/json/AuthorisationCaseField.json
> +    "CRUD": "R"
resolved

2022-07-06 12:57 UTC, Itay-Kirsh submitted a review, later dismissed

2022-07-06 13:58 UTC, Itay-Kirsh approved these changes

2022-07-06 13:59 UTC, merged