RET-2058: ET3 Notification
hmcts/et-ccd-definitions-scotland pull request #147
Opened 2022-07-15 12:15 UTC by robin-ieong

https://tools.hmcts.net/jira/browse/RET-2058

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-07-15 14:11 UTC, jsinghm13 submitted a review, later dismissed

2022-07-15 14:14 UTC, Itay-Kirsh approved these changes

2022-07-15 14:14 UTC, Itay-Kirsh commented on definitions/json/AuthorisationCaseField.json
> +    "UserRole": "caseworker-employment",
R only user role

2022-07-15 14:26 UTC, hsjhita commented on definitions/json/AuthorisationCaseField.json
> +    "CRUD": "CRUD"
R permission

2022-07-15 14:27 UTC, hsjhita commented on definitions/json/AuthorisationCaseField.json
> +    "CRUD": "CRUD"
R permission

2022-07-15 14:27 UTC, hsjhita commented on definitions/json/AuthorisationCaseField.json
> +    "CRUD": "CRUD"
R permission

2022-07-15 14:35 UTC, hsjhita commented on definitions/json/CaseEventToFields.json
> +    "DisplayContext": "MANDATORY",
This should be COMPLEX - the fields part of the complexType should then be listed on EventToComplexTypes

2022-07-15 16:21 UTC, jsinghm13 approved these changes

2022-07-18 08:17 UTC, Itay-Kirsh requested changes

2022-07-18 08:17 UTC, Itay-Kirsh commented on definitions/json/AuthorisationCaseField.json
> +    "CRUD": "CRUD"
Shouldn't be CRUD

2022-07-19 14:19 UTC, jsinghm13 commented on definitions/json/AuthorisationCaseField.json
> +    "CRUD": "CRUD"
Updated to read only

2022-07-19 14:30 UTC, Itay-Kirsh approved these changes

2022-07-19 15:38 UTC, jsinghm13 approved these changes

2022-07-19 15:38 UTC, merged