RET-2684: Changed Initial Consideration Before You Start label text
hmcts/et-ccd-definitions-scotland pull request #223
Opened 2022-10-28 11:42 UTC by JackReevies

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RET-2684

### Change description ###

Changed Initial Consideration Before You Start label text

**Does this PR introduce a breaking change?** (check one with "x")

```
[] Yes
[x] No
```

2022-11-02 14:45 UTC, ikirsanov approved these changes

2022-11-02 14:46 UTC, hsjhita commented on definitions/json/CaseField.json
> +    "Label": "<a href=\"/cases/case-details/${[CASE_REFERENCE]}#Documents\">Open the case documents tab here</a>`",
' at the end ?

2022-11-02 14:46 UTC, Itay-Kirsh requested changes

2022-11-02 14:46 UTC, Itay-Kirsh commented on definitions/json/CaseField.json
> +    "Label": "<a href=\"/cases/case-details/${[CASE_REFERENCE]}#Documents\">Open the case documents tab here</a>`",
Was the ` on purpose?

2022-11-07 11:30 UTC, JackReevies commented on definitions/json/CaseField.json
> +    "Label": "<a href=\"/cases/case-details/${[CASE_REFERENCE]}#Documents\">Open the case documents tab here</a>`",
deffo not intentional, good catch

2022-11-07 13:52 UTC, hsjhita approved these changes

2022-11-07 14:31 UTC, Itay-Kirsh approved these changes

2022-11-07 14:47 UTC, merged