RET-3549: Aligning multiple file uploads for applications and notifications
hmcts/et-ccd-definitions-scotland pull request #381
Opened 2023-05-04 19:56 UTC by JackReevies

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RET-3549

### Change description ###

Aligning multiple file uploads for applications and notifications

**Does this PR introduce a breaking change?** (check one with "x")

```
[] Yes
[x] No
```

2023-05-09 10:51 UTC, paul-peasegood approved these changes

2023-05-09 10:51 UTC, paul-peasegood approved these changes

2023-05-10 11:44 UTC, Itay-Kirsh requested changes

2023-05-10 11:44 UTC, Itay-Kirsh commented on definitions/json/EventToComplexTypes.json
> +    "ID": "tseResponseSupportingMaterial",
duplicate

2023-05-10 11:52 UTC, Itay-Kirsh approved these changes

2023-05-10 13:04 UTC, merged