Ret 4284 - Feature flag case file view
hmcts/et-ccd-definitions-scotland pull request #553
Opened 2023-10-11 14:32 UTC by marcjudge

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RET-4284

### Change description ###
Feature flag case file view

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-10-11 16:03 UTC, ss-evoco requested changes

2023-10-11 16:03 UTC, ss-evoco commented on definitions/json/AuthorisationCaseField/AuthorisationCaseField-CaseFileView-nonprod.json.json
File is called ...-nonprod.json.json

2023-10-11 16:03 UTC, ss-evoco commented on definitions/json/Categories/Categories-CaseFileView-nonprod.json
I think you are referring to these changes in CaseField and ComplexTypes. If so, you need to put them in a prod file too.

2023-10-12 07:12 UTC, marcjudge commented on definitions/json/AuthorisationCaseField/AuthorisationCaseField-CaseFileView-nonprod.json.json
Fixed

2023-10-12 07:12 UTC, marcjudge commented on definitions/json/Categories/Categories-CaseFileView-nonprod.json
Done

2023-10-12 10:38 UTC, ss-evoco approved these changes

2023-10-12 10:44 UTC, JackReevies approved these changes

2023-10-12 10:59 UTC, merged