Ret-4616
hmcts/et-ccd-definitions-scotland pull request #644
Opened 2024-01-23 14:16 UTC by lvo700

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/RET-4616

### Change description ###

Adding notes tab to multiples page.

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-01-23 17:43 UTC, JackReevies approved these changes

2024-01-25 10:04 UTC, ss-evoco requested changes

2024-01-25 10:04 UTC, ss-evoco commented on definitions/json/CaseTypeTab/CaseTypeTab.json
> +    "TabDisplayOrder": 3,
Why did you change this ?

2024-01-25 10:05 UTC, ss-evoco approved these changes

2024-01-25 10:19 UTC, merged